server = '10.30.1.19'
username = ''
password = ''
CONTROLCHECKSTATUS = '\x20'
ADAPTERNUM = '\x04'
host_ip = '10.85.11.41'
IPDOG = '\x01'
host_name = ''
PRIMARY_DNS = '59.70.159.10'
dhcp_server = '0.0.0.0'
AUTH_VERSION = '\x0f\x00'
mac = 0x4ccc6a7a0d22
host_os = 'Windows 10'
KEEP_ALIVE_VERSION = '\xdc\x02'
ror_version = False
